baseURL = "https://kuzhao.github.io/"
languageCode = "en-us"
title = "DuckDuck Go!"
canonifyURLs = true
enableEmoji = true
theme="anatole"
[params]
    portrait = "img/021002-O-9999G-015.jpg"
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "AzureLab"
  url = "/azurelab"
  weight = 2

[[params.social]]
    title = "LN"
    url = "https://www.linkedin.com/in/andy-zhao-405a8156"
[[params.social]]
    title = "Github"
    url = "https://github.com/kuzhao"
